apiVersion: v1
kind: Namespace
metadata:
  name: ping-pong
  labels:
    name: ping-pong
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong
  namespace: ping-pong
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: ping-pong
      app.kubernetes.io/name: pong
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: ping-pong
        app.kubernetes.io/name: pong
    spec:
      containers:
        - name: pong
          image: "ping-pong:dev"
          imagePullPolicy: IfNotPresent
          env:
            - name: PONG_SERVER_PORT
              value: "9090"
          command: ["/pong"]
          ports:
            - name: rpc
              containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: pong
  namespace: ping-pong
spec:
  ports:
    - name: rpc
      port: 9090
      targetPort: rpc
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/part-of: ping-pong
    app.kubernetes.io/name: pong
